name: sample

on: [ push]

permissions:
  id-token: write
  contents: read

jobs:
  sample:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::938385028059:role/github-actions-role
          aws-region: ap-northeast-1
      - name: Deploy with AWS CLI
        run: aws s3 ls
